### ISSUE TITLE
April Meeting Agenda and Scheduling

### ISSUE THREAD

**Issue by Westbrook** [w3c/webcomponents-cg#93]
For those of you who would like to take part in the April meeting of the Web Components Community Group, please share your availability [here](https://www.when2meet.com/?24443314-F2EYq) as we work to schedule the right day/time to gather. Don't forget, all WCCG events are listed on [this calendar](https://calendar.google.com/calendar/u/0/embed?src=o25bim5rvcu42mfnqilirpmp44@group.calendar.google.com). 📆

This will be our last session in preparation for the [face-to-face with implementors](https://github.com/WICG/webcomponents/issues/1050) on May 3rd. We can also use it for scheduling any breakout that should happen through the rest of May. 👥 

It'll be great to sync on progress around user story generation and collection for Declarative Custom Elements and Open Styleable Shadow Roots. That leaves only a small number of [action items](https://github.com/WICG/webcomponents/issues/1031#issuecomment-1885640485) from our last face-to-face not covered. 🥳 

Please share your thoughts below as to subjects that you'd like to cover during the February meeting! 🙇🏼

**Comment by trusktr** [comment]
Should first solve declarative templating (including the possibility of Signals in the JS language) before making DCE?

**Comment by nolanlawson** [comment]
I'd like to add @behowell's "Reference Target for Cross-Root ARIA" proposal to the schedule: https://github.com/WICG/aom/pull/207. It's a good time for another round of feedback on it IMO.

/cc @alice @asyncLiz

**Comment by justinfagnani** [comment]
As I wrote in https://github.com/WICG/webcomponents/issues/1050#issuecomment-2073673657

> If we have time, I would like to throw a very early discussion of a DOM update scheduling API on the agenda. This is something that's been top-of-mind for me very recently as I've dug into signals and web components integration, and I think it intersects with template instantiation and declarative custom elements as well. I'll open an issue asap to sketch out what I see as a problem to address.

**Comment by Westbrook** [comment]
Thanks @justinfagnani do you have any specific goals that you'd want to achieve at the CG level with this initial conversation?

**Comment by justinfagnani** [comment]
@Westbrook just initial discussion of the problem and whether a DOM scheduling API would be a good fit.

I put up the issue just now: https://github.com/WICG/webcomponents/issues/1055

**Comment by Westbrook** [comment]
Many thanks to everyone for joining the conversation today! 🍾 

Meeting notes are available [here](https://docs.google.com/document/d/1jOz2Mu8y49j81WPE7__sHkyoUQey6X09JNiYmEh4b1I/edit#heading=h.l7l9re408mq1).

**Decisions**
- @michaelwarren1106 and @knowler to collate Open Styleable use cases and present on Friday
- @justinfagnani to present on "why start with HTML Modules"
- @sorvell to present on constructing the _right_ custom element by default (hopefully)
- There will be a Web Platform Test session next week (led by @keithamus), share your availability https://www.when2meet.com/?24778030-YfMPQ

<details>
    <summary>Meeting chat hidden within...</summary>

You
11:02 AM
https://docs.google.com/document/d/1jOz2Mu8y49j81WPE7__sHkyoUQey6X09JNiYmEh4b1I/edit
https://docs.google.com/document/d/1jOz2Mu8y49j81WPE7__sHkyoUQey6X09JNiYmEh4b1I/edit
Sasha Firsov
11:05 AM
@Keith, plz share the time and link on Discord
Nathan Knowler
11:10 AM
Jesse can we add this to the notes: 
(This is where we’re collecting concrete use cases)
https://github.com/w3c/webcomponents-cg/discussions/92
Nathan Knowler
11:13 AM
Education is one of the needs for this problem too.
Jesse Jurman
11:15 AM
added! Also, anyone is welcome to add / update the notes too :D
(I'll try not to clobber over you 😅)
You
11:17 AM
Templates over elements?
Sasha Firsov
11:18 AM
The conference where I will present <custom-element> DCE:
https://www.xmlprague.cz/

Future presentations:
https://declarative.amsterdam/cfp
Michael Warren
11:22 AM
one other question for the group: how important do we think it is for the use case groupings to distinguish between who the "owner" of things is? like "i am the owner of the external styles and the component", vs "I am the component author and do not own page styles, but want to allow them"
Joe Pea (Joseph Orbegoso Pea)
11:24 AM
I'd volunteer, but I am too busy this particular week.

Justin there was one meeting before the last two demo meetings where we talked about use cases.
You
11:25 AM
He's not _wrong_....
Michael Warren
11:27 AM
HTML Modules imo is a great "phase 1" of DCE
Owen Buckley
11:27 AM
+1
Steve Orvell
11:28 AM
Abstract use cases:
* want rich UI without script
* want more beginner friendly rich UI authoring
Michael Warren
11:34 AM
https://github.com/facebook/react/issues/28938
Keith Cirkel
11:34 AM
btw Michael your mic is clipping. Might be too high gain?
You
11:34 AM
Like 18, 17, and 16 before it 🤪
Rob Eisenberg
11:36 AM
Cross-root Aria and CSS Slot Content Detection were high on our TPAC list. Should we discuss these at the f2f?
Steve Orvell
11:36 AM
^^ I think these are on the topic list.
Rob Eisenberg
11:37 AM
Great. Just wanted to make sure we kept following up on the stuff we previously called out.
Sasha Firsov
11:38 AM
REact vs DCE speed is non-existing argument, see the B demo on https://unpkg.com/@epa-wg/custom-element@0.0.20/demo/data-slices.html
Nolan Lawson
11:39 AM
FYI: https://custom-elements-everywhere.com/
Joe Pea (Joseph Orbegoso Pea)
11:40 AM
I just got Fathom.video to record the video a few minutes ago. It won't be the whole call, but lets see how good the notes it takes are.
Dang if only Fathom was in the use case meeting, we wouldn't need someone to recall all that. :D
Nolan Lawson
11:42 AM
We do this at Salesforce through DOM patching basically
Pascal Vos
11:44 AM
i wonder if you would allow declarative registry you could wrap a framework would work. like input finding its closest form
Owen Buckley
11:49 AM
can folks go on mute?  hard to hear the convo
Michael Warren
11:57 AM
@sheet and :has-slotted
Owen Buckley
11:58 AM
would be good to share those details in the discrod for anyone who meets the qualifications :D
Steve Orvell
11:59 AM
For anyone interested, we didn't get to discuss this: https://github.com/WICG/webcomponents/issues/1055

</details>

**Comment by trusktr** [comment]
Here is what Fathom generated from the video speech (sorry, I was only able to cover the meeting from 8:35am onward):

Web Components CG - April 29
VIEW RECORDING: https://fathom.video/share/en37N_QRKfg_m5db-S1w94vz8HUzLx2r

# Meeting Purpose:

Discuss scopes custom element registry proposal, getting framework buy-in, and increasing web components presence in the CSS working group.

# Key Takeaways

  - The scopes custom element registry proposal needs more consideration around inter-HTML upgrades and disconnected trees.
  - We should write web platform tests to clarify expected behavior and drive discussion.
  - Increased outreach and collaboration with frameworks like React will help adoption.
  - We need more presence in the CSS working group to raise web components considerations.

# Topics:

## Scopes Custom Element Registry Proposal

  - The proposal needs more consideration around inter-HTML upgrades and disconnected trees. The current design may not handle these cases as expected.
  - We should write web platform tests to clarify expected behavior and drive discussion on requirements.
  - For the next implementer meeting, we'll revisit requirements around inter-HTML upgrades and disconnected trees.

## Framework Collaboration

  - We should increase outreach and send patches to frameworks like React to ease adoption of new web components features. This will help with political issues.
  - For MicroFrontends, we can avoid custom element name conflicts by prefixing component names per app instance. But this is a pain point we can fix.
  - Ideal solutions will allow frameworks like React to work with new web components features without code changes. This will accelerate adoption.

## CSS Working Group Presence

  - We need more presence in the CSS Working Group to raise web components considerations early.
  - Steve Orvell will check if meetings are open for us to join.
  - We'll reach out to existing members like Leah to increase participation.

# Next Steps:

  - Steve to raise concerns around inter-HTML upgrades for scopes proposal at next implementer meeting.
  - Justin to revisit requirements around disconnected trees.
  - Keith to hold web platform testing session to drive test coverage.
  - Steve to check on joining CSS Working Group meetings.
  - Reach out to existing members like Leah to participate more actively.

# Action Items

  - [ ] Contribute patches and tests to frameworks to help with scoped custom element adoption, where feasible - WATCH (30 secs): https://fathom.video/share/en37N_QRKfg_m5db-S1w94vz8HUzLx2r?timestamp=456.9999
  - [ ] Create a clear use case document outlining how scoped custom elements should behave when moved between shadow roots and lead a section with implementers at the next meeting to discuss scoped custom element design - WATCH (30 secs): https://fathom.video/share/en37N_QRKfg_m5db-S1w94vz8HUzLx2r?timestamp=886.0799
  - [ ] Reach out to Leah from the CSS working group to discuss potential web component issues - WATCH (30 secs): https://fathom.video/share/en37N_QRKfg_m5db-S1w94vz8HUzLx2r?timestamp=1159.759899
  - [ ] Investigate options for increasing participation in the CSS Working Group to represent web component interests - WATCH (30 secs): https://fathom.video/share/en37N_QRKfg_m5db-S1w94vz8HUzLx2r?timestamp=1176.1599
